export interface EmojiItem {
  key: string;
  name: string;
  value: string;
  type: 'emoji';
}

export interface EmojiCategory {
  key: string;
  name: string;
  icon: string;
}

// 表情分类
export const emojiCategories: EmojiCategory[] = [
  { key: 'recent', name: '最近使用', icon: '🕒' },
  { key: 'favorite', name: '收藏', icon: '⭐' },
  { key: 'emoji', name: '表情', icon: '😀' },
  { key: 'people', name: '人物', icon: '👥' },
  { key: 'animal', name: '动物', icon: '🐱' },
  { key: 'food', name: '食物', icon: '🍔' },
  { key: 'activity', name: '活动', icon: '⚽' },
  { key: 'travel', name: '旅行', icon: '✈️' },
  { key: 'object', name: '物品', icon: '💡' },
  { key: 'symbol', name: '符号', icon: '💕' }
];

// 表情数据
export const emojiData: Record<string, EmojiItem[]> = {
  recent: [], // 最近使用的表情，将通过 localStorage 动态获取
  favorite: [], // 收藏的表情，将通过 localStorage 动态获取
  emoji: [
    { key: 'smile', name: '微笑', value: '😀', type: 'emoji' },
    { key: 'laugh', name: '大笑', value: '😄', type: 'emoji' },
    { key: 'joy', name: '笑哭', value: '😂', type: 'emoji' },
    { key: 'heart_eyes', name: '爱心眼', value: '😍', type: 'emoji' },
    { key: 'kissing', name: '亲吻', value: '😘', type: 'emoji' },
    { key: 'wink', name: '眨眼', value: '😉', type: 'emoji' },
    { key: 'thinking', name: '思考', value: '🤔', type: 'emoji' },
    { key: 'worried', name: '担心', value: '😟', type: 'emoji' },
    { key: 'angry', name: '生气', value: '😠', type: 'emoji' },
    { key: 'cool', name: '酷', value: '😎', type: 'emoji' },
    { key: 'crazy', name: '疯狂', value: '🤪', type: 'emoji' },
    { key: 'money', name: '发财', value: '🤑', type: 'emoji' },
    { key: 'drool', name: '流口水', value: '🤤', type: 'emoji' },
    { key: 'sleep', name: '睡觉', value: '😴', type: 'emoji' },
    { key: 'mask', name: '口罩', value: '😷', type: 'emoji' },
    { key: 'sick', name: '生病', value: '🤒', type: 'emoji' },
    { key: 'devil', name: '恶魔', value: '😈', type: 'emoji' },
    { key: 'alien', name: '外星人', value: '👽', type: 'emoji' },
    { key: 'ghost', name: '鬼魂', value: '👻', type: 'emoji' },
    { key: 'robot', name: '机器人', value: '🤖', type: 'emoji' },
    { key: 'poop', name: '便便', value: '💩', type: 'emoji' },
    { key: 'clown', name: '小丑', value: '🤡', type: 'emoji' },
    { key: 'skull', name: '骷髅', value: '💀', type: 'emoji' },
    { key: 'kiss_heart', name: '飞吻', value: '💋', type: 'emoji' },
    { key: 'love', name: '爱情', value: '🥰', type: 'emoji' },
    { key: 'sad', name: '伤心', value: '😢', type: 'emoji' },
    { key: 'cry', name: '大哭', value: '😭', type: 'emoji' },
    { key: 'fearful', name: '害怕', value: '😨', type: 'emoji' },
    { key: 'cold_sweat', name: '冷汗', value: '😰', type: 'emoji' },
    { key: 'scream', name: '尖叫', value: '😱', type: 'emoji' },
    { key: 'zany', name: '搞怪', value: '🤪', type: 'emoji' },
    { key: 'shushing', name: '嘘声', value: '🤫', type: 'emoji' },
    { key: 'lying', name: '说谎', value: '🤥', type: 'emoji' },
    { key: 'exploding', name: '爆炸头', value: '🤯', type: 'emoji' },
    { key: 'cowboy', name: '牛仔', value: '🤠', type: 'emoji' },
    { key: 'partying', name: '派对', value: '🥳', type: 'emoji' },
    { key: 'disguised', name: '伪装', value: '🥸', type: 'emoji' },
    { key: 'pleading', name: '恳求', value: '🥺', type: 'emoji' },
    { key: 'yawning', name: '打哈欠', value: '🥱', type: 'emoji' },
    { key: 'smirking', name: '得意', value: '😏', type: 'emoji' },
    { key: 'unamused', name: '不高兴', value: '😒', type: 'emoji' },
    { key: 'rolling_eyes', name: '翻白眼', value: '🙄', type: 'emoji' },
    { key: 'grimacing', name: '扭曲', value: '😬', type: 'emoji' },
    { key: 'flushed', name: '脸红', value: '😳', type: 'emoji' },
    { key: 'zipper', name: '拉链嘴', value: '🤐', type: 'emoji' },
    { key: 'relieved', name: '如释重负', value: '😌', type: 'emoji' },
    { key: 'innocent', name: '天使', value: '😇', type: 'emoji' },
    { key: 'star_struck', name: '星星眼', value: '🤩', type: 'emoji' },
    { key: 'nerd', name: '书呆子', value: '🤓', type: 'emoji' },
    { key: 'dizzy', name: '眩晕', value: '😵', type: 'emoji' },
    { key: 'nauseated', name: '恶心', value: '🤢', type: 'emoji' },
    { key: 'vomiting', name: '呕吐', value: '🤮', type: 'emoji' },
    { key: 'sneezing', name: '打喷嚏', value: '🤧', type: 'emoji' },
    { key: 'hot', name: '发烧', value: '🥵', type: 'emoji' },
    { key: 'cold', name: '寒冷', value: '🥶', type: 'emoji' },
    { key: 'woozy', name: '晕头转向', value: '🥴', type: 'emoji' },
    { key: 'knocked_out', name: '昏迷', value: '😵', type: 'emoji' },
    { key: 'heart_face', name: '爱心脸', value: '🥰', type: 'emoji' },
    { key: 'saluting', name: '敬礼', value: '🫡', type: 'emoji' },
    { key: 'face_holding_back_tears', name: '强忍泪水', value: '🥹', type: 'emoji' },
    { key: 'dotted_line_face', name: '虚线脸', value: '🫥', type: 'emoji' },
    { key: 'face_in_clouds', name: '云中脸', value: '😶‍🌫️', type: 'emoji' },
    { key: 'melting', name: '融化', value: '🫠', type: 'emoji' },
    { key: 'peeking', name: '偷看', value: '🫣', type: 'emoji' },
    { key: 'hand_over_mouth', name: '捂嘴', value: '🫢', type: 'emoji' }

  ],
  people: [
    { key: 'wave', name: '招手', value: '👋', type: 'emoji' },
    { key: 'clap', name: '鼓掌', value: '👏', type: 'emoji' },
    { key: 'thumbs_up', name: '点赞', value: '👍', type: 'emoji' },
    { key: 'victory', name: '胜利', value: '✌️', type: 'emoji' },
    { key: 'muscle', name: '肌肉', value: '💪', type: 'emoji' },
    { key: 'pray', name: '祈祷', value: '🙏', type: 'emoji' },
    { key: 'dancer', name: '跳舞', value: '💃', type: 'emoji' },
    { key: 'ninja', name: '忍者', value: '🥷', type: 'emoji' },
    { key: 'astronaut', name: '宇航员', value: '👨‍🚀', type: 'emoji' },
    { key: 'superhero', name: '超级英雄', value: '🦸', type: 'emoji' },
    { key: 'baby', name: '婴儿', value: '👶', type: 'emoji' },
    { key: 'boy', name: '男孩', value: '👦', type: 'emoji' },
    { key: 'girl', name: '女孩', value: '👧', type: 'emoji' },
    { key: 'man', name: '男人', value: '👨', type: 'emoji' },
    { key: 'woman', name: '女人', value: '👩', type: 'emoji' },
    { key: 'old_man', name: '老人', value: '👴', type: 'emoji' },
    { key: 'old_woman', name: '老太', value: '👵', type: 'emoji' },
    { key: 'police', name: '警察', value: '👮', type: 'emoji' },
    { key: 'detective', name: '侦探', value: '🕵️', type: 'emoji' },
    { key: 'guard', name: '卫兵', value: '💂', type: 'emoji' },
    { key: 'construction_worker', name: '工人', value: '👷', type: 'emoji' },
    { key: 'prince', name: '王子', value: '🤴', type: 'emoji' },
    { key: 'princess', name: '公主', value: '👸', type: 'emoji' },
    { key: 'mage', name: '魔法师', value: '🧙', type: 'emoji' },
    { key: 'fairy', name: '仙女', value: '🧚', type: 'emoji' },
    { key: 'vampire', name: '吸血鬼', value: '🧛', type: 'emoji' },
    { key: 'mermaid', name: '美人鱼', value: '🧜', type: 'emoji' },
    { key: 'elf', name: '精灵', value: '🧝', type: 'emoji' },
    { key: 'genie', name: '精灵', value: '🧞', type: 'emoji' },
    { key: 'zombie', name: '僵尸', value: '🧟', type: 'emoji' }
  ],
  animal: [
    { key: 'cat', name: '猫咪', value: '🐱', type: 'emoji' },
    { key: 'dog', name: '狗狗', value: '🐶', type: 'emoji' },
    { key: 'unicorn', name: '独角兽', value: '🦄', type: 'emoji' },
    { key: 'panda', name: '熊猫', value: '🐼', type: 'emoji' },
    { key: 'penguin', name: '企鹅', value: '🐧', type: 'emoji' },
    { key: 'butterfly', name: '蝴蝶', value: '🦋', type: 'emoji' },
    { key: 'dolphin', name: '海豚', value: '🐬', type: 'emoji' },
    { key: 'owl', name: '猫头鹰', value: '🦉', type: 'emoji' },
    { key: 'mouse', name: '老鼠', value: '🐭', type: 'emoji' },
    { key: 'hamster', name: '仓鼠', value: '🐹', type: 'emoji' },
    { key: 'rabbit', name: '兔子', value: '🐰', type: 'emoji' },
    { key: 'fox', name: '狐狸', value: '🦊', type: 'emoji' },
    { key: 'bear', name: '熊', value: '🐻', type: 'emoji' },
    { key: 'koala', name: '考拉', value: '🐨', type: 'emoji' },
    { key: 'tiger', name: '老虎', value: '🐯', type: 'emoji' },
    { key: 'lion', name: '狮子', value: '🦁', type: 'emoji' },
    { key: 'cow', name: '奶牛', value: '🐮', type: 'emoji' },
    { key: 'pig', name: '猪', value: '🐷', type: 'emoji' },
    { key: 'frog', name: '青蛙', value: '🐸', type: 'emoji' },
    { key: 'monkey', name: '猴子', value: '🐵', type: 'emoji' },
    { key: 'chicken', name: '鸡', value: '🐔', type: 'emoji' },
    { key: 'duck', name: '鸭子', value: '🦆', type: 'emoji' },
    { key: 'eagle', name: '鹰', value: '🦅', type: 'emoji' },
    { key: 'dove', name: '鸽子', value: '🕊️', type: 'emoji' },
    { key: 'snail', name: '蜗牛', value: '🐌', type: 'emoji' },
    { key: 'octopus', name: '章鱼', value: '🐙', type: 'emoji' },
    { key: 'fish', name: '鱼', value: '🐟', type: 'emoji' },
    { key: 'shark', name: '鲨鱼', value: '🦈', type: 'emoji' },
    { key: 'whale', name: '鲸鱼', value: '🐳', type: 'emoji' },
    { key: 'turtle', name: '乌龟', value: '🐢', type: 'emoji' }
  ],
  food: [
    { key: 'pizza', name: '披萨', value: '🍕', type: 'emoji' },
    { key: 'burger', name: '汉堡', value: '🍔', type: 'emoji' },
    { key: 'ramen', name: '拉面', value: '🍜', type: 'emoji' },
    { key: 'sushi', name: '寿司', value: '🍣', type: 'emoji' },
    { key: 'ice_cream', name: '冰淇淋', value: '🍦', type: 'emoji' },
    { key: 'cake', name: '蛋糕', value: '🎂', type: 'emoji' },
    { key: 'rice', name: '米饭', value: '🍚', type: 'emoji' },
    { key: 'curry', name: '咖喱', value: '🍛', type: 'emoji' },
    { key: 'noodles', name: '面条', value: '🍝', type: 'emoji' },
    { key: 'fried_shrimp', name: '炸虾', value: '🍤', type: 'emoji' },
    { key: 'bento', name: '便当', value: '🍱', type: 'emoji' },
    { key: 'dumpling', name: '饺子', value: '🥟', type: 'emoji' },
    { key: 'fortune_cookie', name: '幸运饼', value: '🥠', type: 'emoji' },
    { key: 'bread', name: '面包', value: '🍞', type: 'emoji' },
    { key: 'croissant', name: '牛角包', value: '🥐', type: 'emoji' },
    { key: 'bagel', name: '百吉饼', value: '🥯', type: 'emoji' },
    { key: 'pancakes', name: '煎饼', value: '🥞', type: 'emoji' },
    { key: 'waffle', name: '华夫饼', value: '🧇', type: 'emoji' },
    { key: 'cheese', name: '奶酪', value: '🧀', type: 'emoji' },
    { key: 'meat', name: '肉', value: '🍖', type: 'emoji' },
    { key: 'poultry_leg', name: '鸡腿', value: '🍗', type: 'emoji' },
    { key: 'bacon', name: '培根', value: '🥓', type: 'emoji' },
    { key: 'hot_dog', name: '热狗', value: '🌭', type: 'emoji' },
    { key: 'sandwich', name: '三明治', value: '🥪', type: 'emoji' },
    { key: 'taco', name: '墨西哥卷', value: '🌮', type: 'emoji' },
    { key: 'burrito', name: '玉米卷', value: '🌯', type: 'emoji' },
    { key: 'salad', name: '沙拉', value: '🥗', type: 'emoji' },
    { key: 'popcorn', name: '爆米花', value: '🍿', type: 'emoji' },
    { key: 'cookie', name: '饼干', value: '🍪', type: 'emoji' },
    { key: 'chocolate', name: '巧克力', value: '🍫', type: 'emoji' }
  ],
  activity: [
    { key: 'soccer', name: '足球', value: '⚽', type: 'emoji' },
    { key: 'basketball', name: '篮球', value: '🏀', type: 'emoji' },
    { key: 'game', name: '游戏', value: '🎮', type: 'emoji' },
    { key: 'music', name: '音乐', value: '🎵', type: 'emoji' },
    { key: 'movie', name: '电影', value: '🎬', type: 'emoji' },
    { key: 'baseball', name: '棒球', value: '⚾', type: 'emoji' },
    { key: 'tennis', name: '网球', value: '🎾', type: 'emoji' },
    { key: 'volleyball', name: '排球', value: '🏐', type: 'emoji' },
    { key: 'rugby', name: '橄榄球', value: '🏉', type: 'emoji' },
    { key: 'badminton', name: '羽毛球', value: '🏸', type: 'emoji' },
    { key: 'ping_pong', name: '乒乓球', value: '🏓', type: 'emoji' },
    { key: 'boxing', name: '拳击', value: '🥊', type: 'emoji' },
    { key: 'martial_arts', name: '武术', value: '🥋', type: 'emoji' },
    { key: 'fishing', name: '钓鱼', value: '🎣', type: 'emoji' },
    { key: 'running', name: '跑步', value: '🏃', type: 'emoji' },
    { key: 'swimming', name: '游泳', value: '🏊', type: 'emoji' },
    { key: 'surfing', name: '冲浪', value: '🏄', type: 'emoji' },
    { key: 'skiing', name: '滑雪', value: '⛷️', type: 'emoji' },
    { key: 'ice_skating', name: '溜冰', value: '⛸️', type: 'emoji' },
    { key: 'golf', name: '高尔夫', value: '⛳', type: 'emoji' },
    { key: 'bowling', name: '保龄球', value: '🎳', type: 'emoji' },
    { key: 'chess', name: '国际象棋', value: '♟️', type: 'emoji' },
    { key: 'dart', name: '飞镖', value: '🎯', type: 'emoji' },
    { key: 'puzzle', name: '拼图', value: '🧩', type: 'emoji' },
    { key: 'art', name: '艺术', value: '🎨', type: 'emoji' },
    { key: 'circus', name: '马戏团', value: '🎪', type: 'emoji' },
    { key: 'theater', name: '剧院', value: '🎭', type: 'emoji' },
    { key: 'microphone', name: '麦克风', value: '🎤', type: 'emoji' },
    { key: 'headphone', name: '耳机', value: '🎧', type: 'emoji' },
    { key: 'saxophone', name: '萨克斯', value: '🎷', type: 'emoji' }
  ],
  travel: [
    { key: 'airplane', name: '飞机', value: '✈️', type: 'emoji' },
    { key: 'car', name: '汽车', value: '🚗', type: 'emoji' },
    { key: 'mountain', name: '山', value: '⛰️', type: 'emoji' },
    { key: 'beach', name: '海滩', value: '🏖️', type: 'emoji' },
    { key: 'train', name: '火车', value: '🚂', type: 'emoji' },
    { key: 'bus', name: '公交车', value: '🚌', type: 'emoji' },
    { key: 'taxi', name: '出租车', value: '🚕', type: 'emoji' },
    { key: 'motorcycle', name: '摩托车', value: '🏍️', type: 'emoji' },
    { key: 'bicycle', name: '自行车', value: '🚲', type: 'emoji' },
    { key: 'ship', name: '轮船', value: '🚢', type: 'emoji' },
    { key: 'rocket', name: '火箭', value: '🚀', type: 'emoji' },
    { key: 'helicopter', name: '直升机', value: '🚁', type: 'emoji' },
    { key: 'tram', name: '电车', value: '🚊', type: 'emoji' },
    { key: 'station', name: '车站', value: '🚉', type: 'emoji' },
    { key: 'hotel', name: '酒店', value: '🏨', type: 'emoji' },
    { key: 'camping', name: '露营', value: '⛺', type: 'emoji' },
    { key: 'bridge', name: '桥', value: '🌉', type: 'emoji' },
    { key: 'fountain', name: '喷泉', value: '⛲', type: 'emoji' },
    { key: 'castle', name: '城堡', value: '🏰', type: 'emoji' },
    { key: 'temple', name: '寺庙', value: '⛩️', type: 'emoji' },
    { key: 'church', name: '教堂', value: '⛪', type: 'emoji' },
    { key: 'mosque', name: '清真寺', value: '🕌', type: 'emoji' },
    { key: 'synagogue', name: '犹太教堂', value: '🕍', type: 'emoji' },
    { key: 'cityscape', name: '城市', value: '🌆', type: 'emoji' },
    { key: 'night_sky', name: '夜空', value: '🌃', type: 'emoji' },
    { key: 'sunrise', name: '日出', value: '🌅', type: 'emoji' },
    { key: 'sunset', name: '日落', value: '🌇', type: 'emoji' },
    { key: 'desert', name: '沙漠', value: '🏜️', type: 'emoji' },
    { key: 'island', name: '岛屿', value: '🏝️', type: 'emoji' },
    { key: 'volcano', name: '火山', value: '🌋', type: 'emoji' }
  ],
  object: [
    { key: 'gift', name: '礼物', value: '🎁', type: 'emoji' },
    { key: 'camera', name: '相机', value: '📷', type: 'emoji' },
    { key: 'book', name: '书', value: '📚', type: 'emoji' },
    { key: 'phone', name: '手机', value: '📱', type: 'emoji' },
    { key: 'computer', name: '电脑', value: '💻', type: 'emoji' },
    { key: 'tv', name: '电视', value: '📺', type: 'emoji' },
    { key: 'radio', name: '收音机', value: '📻', type: 'emoji' },
    { key: 'clock', name: '时钟', value: '⏰', type: 'emoji' },
    { key: 'watch', name: '手表', value: '⌚', type: 'emoji' },
    { key: 'hourglass', name: '沙漏', value: '⌛', type: 'emoji' },
    { key: 'calendar', name: '日历', value: '📅', type: 'emoji' },
    { key: 'pencil', name: '铅笔', value: '✏️', type: 'emoji' },
    { key: 'pen', name: '钢笔', value: '🖊️', type: 'emoji' },
    { key: 'paintbrush', name: '画笔', value: '🖌️', type: 'emoji' },
    { key: 'crayon', name: '蜡笔', value: '🖍️', type: 'emoji' },
    { key: 'paperclip', name: '回形针', value: '📎', type: 'emoji' },
    { key: 'scissors', name: '剪刀', value: '✂️', type: 'emoji' },
    { key: 'key', name: '钥匙', value: '🔑', type: 'emoji' },
    { key: 'lock', name: '锁', value: '🔒', type: 'emoji' },
    { key: 'hammer', name: '锤子', value: '🔨', type: 'emoji' },
    { key: 'wrench', name: '扳手', value: '🔧', type: 'emoji' },
    { key: 'toolbox', name: '工具箱', value: '🧰', type: 'emoji' },
    { key: 'microscope', name: '显微镜', value: '🔬', type: 'emoji' },
    { key: 'telescope', name: '望远镜', value: '🔭', type: 'emoji' },
    { key: 'satellite', name: '卫星', value: '📡', type: 'emoji' },
    { key: 'syringe', name: '注射器', value: '💉', type: 'emoji' },
    { key: 'pill', name: '药丸', value: '💊', type: 'emoji' },
    { key: 'money_bag', name: '钱袋', value: '💰', type: 'emoji' },
    { key: 'credit_card', name: '信用卡', value: '💳', type: 'emoji' },
    { key: 'gem', name: '宝石', value: '💎', type: 'emoji' }
  ],
  symbol: [
    { key: 'heart', name: '爱心', value: '❤️', type: 'emoji' },
    { key: 'star', name: '星星', value: '⭐', type: 'emoji' },
    { key: 'sparkles', name: '闪光', value: '✨', type: 'emoji' },
    { key: 'fire', name: '火焰', value: '🔥', type: 'emoji' },
    { key: 'rainbow', name: '彩虹', value: '🌈', type: 'emoji' },
    { key: 'peace', name: '和平', value: '☮️', type: 'emoji' },
    { key: 'infinity', name: '无限', value: '♾️', type: 'emoji' },
    { key: 'recycle', name: '回收', value: '♻️', type: 'emoji' },
    { key: 'warning', name: '警告', value: '⚠️', type: 'emoji' },
    { key: 'prohibited', name: '禁止', value: '🚫', type: 'emoji' },
    { key: 'radioactive', name: '辐射', value: '☢️', type: 'emoji' },
    { key: 'biohazard', name: '生物危害', value: '☣️', type: 'emoji' },
    { key: 'yin_yang', name: '阴阳', value: '☯️', type: 'emoji' },
    { key: 'cross', name: '十字', value: '✝️', type: 'emoji' },
    { key: 'star_and_crescent', name: '星月', value: '☪️', type: 'emoji' },
    { key: 'wheel_of_dharma', name: '法轮', value: '☸️', type: 'emoji' },
    { key: 'star_of_david', name: '大卫星', value: '✡️', type: 'emoji' },
    { key: 'om', name: '奥姆', value: '🕉️', type: 'emoji' },
    { key: 'menorah', name: '烛台', value: '🕎', type: 'emoji' },
    { key: 'check', name: '对勾', value: '✔️', type: 'emoji' },
    { key: 'cross_mark', name: '叉', value: '❌', type: 'emoji' },
    { key: 'question', name: '问号', value: '❓', type: 'emoji' },
    { key: 'exclamation', name: '感叹号', value: '❗', type: 'emoji' },
    { key: 'plus', name: '加号', value: '➕', type: 'emoji' },
    { key: 'minus', name: '减号', value: '➖', type: 'emoji' },
    { key: 'multiply', name: '乘号', value: '✖️', type: 'emoji' },
    { key: 'divide', name: '除号', value: '➗', type: 'emoji' },
    { key: 'arrow_up', name: '向上', value: '⬆️', type: 'emoji' },
    { key: 'arrow_down', name: '向下', value: '⬇️', type: 'emoji' },
    { key: 'arrow_left', name: '向左', value: '⬅️', type: 'emoji' },
    { key: 'arrow_right', name: '向右', value: '➡️', type: 'emoji' },
    { key: 'arrow_upper_right', name: '右上', value: '↗️', type: 'emoji' },
    { key: 'arrow_lower_right', name: '右下', value: '↘️', type: 'emoji' },
    { key: 'arrow_lower_left', name: '左下', value: '↙️', type: 'emoji' },
    { key: 'arrow_upper_left', name: '左上', value: '↖️', type: 'emoji' },
    { key: 'arrow_left_right', name: '左右', value: '↔️', type: 'emoji' },
    { key: 'arrow_up_down', name: '上下', value: '↕️', type: 'emoji' },
    { key: 'clockwise', name: '顺时针', value: '🔄', type: 'emoji' },
    { key: 'counterclockwise', name: '逆时针', value: '🔃', type: 'emoji' },
    { key: 'back', name: '返回', value: '🔙', type: 'emoji' },
    { key: 'end', name: '结束', value: '🔚', type: 'emoji' },
    { key: 'on', name: '开启', value: '🔛', type: 'emoji' },
    { key: 'soon', name: '即将', value: '🔜', type: 'emoji' },
    { key: 'top', name: '顶部', value: '🔝', type: 'emoji' },
    { key: 'place_of_worship', name: '礼拜', value: '🛐', type: 'emoji' },
    { key: 'atom', name: '原子', value: '⚛️', type: 'emoji' },
    { key: 'dotted_six', name: '点六', value: '⚅', type: 'emoji' },
    { key: 'chess_king', name: '国王', value: '♔', type: 'emoji' },
    { key: 'chess_queen', name: '皇后', value: '♕', type: 'emoji' },
    { key: 'chess_rook', name: '城堡', value: '♖', type: 'emoji' },
    { key: 'chess_bishop', name: '主教', value: '♗', type: 'emoji' },
    { key: 'chess_knight', name: '骑士', value: '♘', type: 'emoji' },
    { key: 'chess_pawn', name: '兵', value: '♙', type: 'emoji' },
    { key: 'spade', name: '黑桃', value: '♠️', type: 'emoji' },
    { key: 'heart_suit', name: '红心', value: '♥️', type: 'emoji' },
    { key: 'diamond', name: '方块', value: '♦️', type: 'emoji' },
    { key: 'club', name: '梅花', value: '♣️', type: 'emoji' },
    { key: 'hot_springs', name: '温泉', value: '♨️', type: 'emoji' },
    { key: 'white_circle', name: '白圈', value: '⚪', type: 'emoji' },
    { key: 'black_circle', name: '黑圈', value: '⚫', type: 'emoji' },
    { key: 'white_square', name: '白方', value: '⬜', type: 'emoji' },
    { key: 'black_square', name: '黑方', value: '⬛', type: 'emoji' },
    { key: 'triangle_up', name: '上三角', value: '▲', type: 'emoji' },
    { key: 'triangle_down', name: '下三角', value: '▼', type: 'emoji' },
    { key: 'diamond_shape', name: '菱形', value: '💠', type: 'emoji' },
    { key: 'fleur_de_lis', name: '百合花', value: '⚜️', type: 'emoji' },
    { key: 'trident', name: '三叉戟', value: '🔱', type: 'emoji' },
    { key: 'name_badge', name: '名牌', value: '📛', type: 'emoji' },
    { key: 'beginner', name: '新手', value: '🔰', type: 'emoji' },
    { key: 'chart', name: '图表', value: '📊', type: 'emoji' },
    { key: 'currency_exchange', name: '货币兑换', value: '💱', type: 'emoji' },
    { key: 'heavy_dollar', name: '美元', value: '💲', type: 'emoji' },
    { key: 'medical', name: '医疗', value: '⚕️', type: 'emoji' },
    { key: 'scales', name: '天平', value: '⚖️', type: 'emoji' },
    { key: 'anchor', name: '锚', value: '⚓', type: 'emoji' },
    { key: 'crossed_swords', name: '双剑', value: '⚔️', type: 'emoji' },
    { key: 'staff_of_aesculapius', name: '医杖', value: '⚚', type: 'emoji' },
    { key: 'gear', name: '齿轮', value: '⚙️', type: 'emoji' },
    { key: 'alembic', name: '蒸馏器', value: '⚗️', type: 'emoji' },
    { key: 'scales_of_justice', name: '正义天平', value: '⚖️', type: 'emoji' }
  ]
};